WebSqlServerDocumentator/Controllers/DatabaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SqlServerDocumentator;
using SqlServerDocumentator.DocumentedDatabaseObjects;

namespace WebSqlServerDocumentator.Controllers
{
	public class DatabaseController : Controller
	{
		private IDocumentator _documentator;

		public DatabaseController(IDocumentator documentator)
		{
			this._documentator = documentator;
		}

		[Route("{serverName}/databases")]
		public IActionResult Index(string serverName)
		{
			return View(this._documentator.GetDatabases(serverName));
		}

		[Route("{serverName}/databases")]
		[HttpPost]
		public IActionResult Save(DocumentedDatabase database)
		{
			//return View(this._documentator.GetDatabases(serverName));
			return View("Index", this._documentator.GetDatabases(database.ServerName));
		}

		[Route("/{serverName}/{databaseName}/tables")]
		public IActionResult Tables(string serverName, string databaseName)
		{
			return View(this._documentator.GetTables(serverName, databaseName));
		}

		[Route("/{serverName}/{databaseName}/views")]
		public IActionResult Views(string serverName, string databaseName)
		{
			return View(this._documentator.GetViews(serverName, databaseName));
		}

		[Route("/{serverName}/{databaseName}/storedProcedures")]
		public IActionResult StoredProcedures(string serverName, string databaseName)
		{
			return View(this._documentator.GetStoredProcedures(serverName, databaseName));
		}
    }
}

WebSqlServerDocumentator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebSqlServerDocumentator.Models;
using SqlServerDocumentator;

namespace WebSqlServerDocumentator.Controllers
{
    public class HomeController : Controller
    {
        private IDocumentator _documentator;

        public HomeController(IDocumentator documentator)
        {
            _documentator = documentator;
        }

        [Route("")]
        public IActionResult Index()
        {
            return View(_documentator.GetServers());
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebSqlServerDocumentator/Views/Home/Index.cshtml
@model IEnumerable<SqlServerDocumentator.DocumentedDatabaseObjects.DocumentedServer>

@{
    ViewData["Title"] = "Home Page";
}

<h2>Servers</h2>
<div class="servers">
    @foreach (var item in Model)
    {
        <documented-server :name="'@item.Name'" :description="'@item.Description'" :display-name="'@item.DisplayName'" :url="'@Url.Action("Index", "Database", new { serverName = item.Name })'"></documented-server>
    }
</div>
@section scripts {
    <script type="text/javascript">
        Vue.component('documented-server', {
            props: {
                name: { type: String, default: '' },
                displayName: { type: String, default: '' },
                description: { type: String, default: '' },
                url: { type: String, default: '' }
            },
            template: '<div>{{displayName}} - {{name}} || {{description}} || <a :href="url">Explore</a></div>'
        });

        new Vue(
            {
                el: '.servers'
            });
    </script>
}